### ISSUE TITLE
compile error 

### ISSUE THREAD

**Issue by feech** [anystub/anystub#2]
During compiling project:
Error:java: Compilation failed: internal java compiler error (on JDK8 up20)

or (on JDK8 up31)
An exception has occurred in the compiler (1.8.0_31). Please file a bug at the Java Developer Connection (http://java.sun.com/webapps/bugreport)  after checking the Bug Parade for duplicates. Include your program and the following diagnostic in your report.  Thank you.
java.lang.AssertionError: Value of x -1
    at com.sun.tools.javac.util.Assert.error(Assert.java:133)
    at com.sun.tools.javac.util.Assert.check(Assert.java:94)
    at com.sun.tools.javac.util.Bits.incl(Bits.java:186)

**Comment by feech** [comment]
because of snakey-yml
it works on JDK8 update 91 and newer
try update

**Comment by feech** [comment]
it also works on Travis with: 

java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)

try to update java
